Custom Properties: `about.css`
ryelle/wordpress-develop pull request #24
Opened 2021-09-14 03:20 UTC by 0aveRyan

# Adds custom properties to `/wp-admin/css/about.css`

The About Page already had a rudementary CSS Custom Properties system, sans our new prefixing. I've migrated to our CSS Custom Properties naming convention with fallbacks to the original properties in the event they were used.

The About Page also requires "WordPress blue", which I've added to Custom Properties as `--wp--brand--blue`.

Trac ticket: https://core.trac.wordpress.org/ticket/49930

2021-09-16 22:51 UTC, ryelle commented
This file is kind of a special case - these custom properties only apply to items in the About section, since they're scoped to `.about__container`. This page is redesigned with each release, and initially these custom properties were introduced so that the page could be "reskinned" (TBH it hasn't really worked out like that, each release's design is more ambitious than the structure allows 🤷🏻 ). Anyway, conceptually I don't think these properties are meant to be `--wp-admin--` props, they're not meant to be overridden by an admin scheme. They probably should have been given some prefix (literally my fault), but they weren't 😅 

So, for this file, I think it's great to use the existing properties like `--wp-admin--surface--background` where applicable, but I wouldn't use the `--wp-admin--` prefix/naming scheme on these. If you want to add a prefix, maybe just `--about-page--[current-name]`.

I also think you can ignore everything below `x.2.0 - Legacy About Styles: Global` -- that has not been in use since … I think a 4.x version. Could you revert those changes here? that should also clean up some of the new properties that were added.

2021-09-30 19:33 UTC, 0aveRyan commented
@ryelle I've swapped `--wp-admin--about-page` for `--about-page`.

Regarding the deprecated styles, if someone has loaded this stylesheet and mirrored 4.x markup structure in a plugin, it seems making the swaps will better preserve backwards compatibility with this new API.

I removed the new, one-off properties related to the abandoned styles and left the other properties from `--about-page` and `--wp-admin` that are used elsewhere. I can fully revert but that was why I'd modded 'em in the first place so want to check before I fully undo.

2021-09-30 20:50 UTC, ryelle requested changes
> Regarding the deprecated styles, if someone has loaded this stylesheet and mirrored 4.x markup structure in a plugin, it seems making the swaps will better preserve backwards compatibility with this new API.

I'm not sure I understand - if a plugin uses the legacy/deprecated structure & style, it will show the old-style about page. If a user has switched over to a different (custom-property-powered) color scheme, like a dark mode, only implementing some of the custom properties could make the legacy page unreadable. It seems to me like leaving this section alone would prevent that, but maybe there's more to it? What do you think?

2021-09-30 20:50 UTC, ryelle commented on src/wp-admin/css/about.css
> -	--nav-current: var(--accent-1);
These nav values should stick around - the navigation colors don't always map to other colors like this (see [5.7](https://core.trac.wordpress.org/browser/branches/5.7/src/wp-admin/css/about.css#L34), [5.6](https://core.trac.wordpress.org/browser/branches/5.6/src/wp-admin/css/about.css#L42))

2021-09-30 20:50 UTC, ryelle commented on src/wp-admin/css/about.css
> +	background: linear-gradient(180deg, var(--about-page--background) 50%, var(--wp-admin--surface--background) 100%);
I think this is reversed? Should it be 
```suggestion
	background: linear-gradient(180deg, var(--wp-admin--surface--background) 50%, var(--about-page--background) 100%);
```

2023-10-18 16:37 UTC, closed without merging